const products = [
  {
    _id: '1',
    name: 'Men White Sneakers',
    image: '/images/image1.jpg',
    description:
      'A pair of round-toe white sneakers, has regular styling, lace-up detail | Synthetic Leather upper | Cushioned footbed | Textured and patterned outsole | Warranty: 3 months | Warranty provided by brand/manufacturer, | brand: Apple',
    category: 'Shoes',
    brand: 'LOCOMOTIVE',
    price: 745,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Men Black Solid Horsebit Loafers',
    image: '/images/image2.jpg',
    description:
      'A pair of round toe black loafers, has regular styling, slip-on detailing | PU upper | Cushioned footbed | Textured and patterned outsole | Warranty: 3 months | Provided by Brand/Manufacturer',
    brand: 'WRONG',
    category: 'Shoes',
    price: 1399,
    countInStock: 7,
    rating: 4.6,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Men Chunky Sneakers',
    image: '/images/image3.jpg',
    description:
      'Upper composed of high quality synthetic leather with mesh underlays for breathability | Lace up design locks your foot across the mid foot work with the laces to help to keep your foot from shifting within the shoe & gives you secure fit.',
    brand: 'HRX by Hrithik Roshan',
    category: 'Shoes',
    price: 929.99,
    countInStock: 5,
    rating: 4.1,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Men Grey Sneakers',
    image: '/images/image4.jpg',
    description:
      'A pair of round toe grey sneakers ,has regular styling | Lace-ups detail | Mesh upper | Cushioned footbed | Textured and patterned outsole | Warranty: 3 months',
    brand: 'Red Tape',
    category: 'Shoes',
    price: 4399,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Men Beige Sneakers',
    image: '/images/image5.jpg',
    description:
      'A pair of round-toe beige sneakers, has regular styling, slip-on detail | Mesh upper | Cushioned footbed | Textured and patterned outsole | Warranty: 3 months | Warranty provided by brand/manufacturer',
    brand: 'WRONG',
    category: 'Shoes',
    price: 1678,
    countInStock: 7,
    rating: 3.7,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Men White Sneakers',
    image: '/images/image6.jpg',
    description:
      'Fusing a modern aesthetic with heritage detailing, the Courtline trainer offers a traditional, sport-inspired cupsole construction executed in premium materials. Softer, hand-feel nappa leather is contrasted with suede overlays to cut a clean look and add a touch of texture.',
    brand: 'Lacoste',
    category: 'Shoes',
    price: 7350,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Men Flex Street Shoe',
    image: '/images/image7.jpg',
    description:
      'Product description: The Lifestyle Shoes from the Flex Street Series sports a modern design and high performance materials that make any kind of activity easier. Features: -Upper is Constructed with knitted fabric, -Cushion collar provides ankle support, -Flexible EVA Sole makes the shoes more comfortable & light weight, -Cup shaped insole gives additional support and comfort.',
    brand: 'HRX by Hrithik Roshan',
    category: 'Shoes',
    price: 1749,
    countInStock: 6,
    rating: 4.6,
    numReviews: 7,
  },
  {
    _id: '8',
    name: 'Men White Baymax Sneakers',
    image: '/images/image8.jpg',
    description:
      'Design Details: A pair of round toe white sneakers ,has regular styling | Lace-ups detail | Synthetic upper | Cushioned footbed | Textured and patterned outsole Warranty: 3 months',
    brand: 'Puma',
    category: 'Shoes',
    price: 3444,
    countInStock: 1,
    rating: 4.8,
    numReviews: 5,
  },
];

export default products;
